# Generated by Django 3.2.16 on 2023-07-09 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salar', models.IntegerField(verbose_name='Текущая зарплата')),
                ('date', models.DateField(verbose_name='Дата следующего повышения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Следующее повывшение',
                'verbose_name_plural': 'Следующие повывшения',
                'ordering': ['id'],
            },
        ),
    ]
