# Generated by Django 3.2.16 on 2023-07-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={},
        ),
    ]
