# Generated by Django 3.2.16 on 2023-07-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_salary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['id'], 'verbose_name': 'Следующее повывшение', 'verbose_name_plural': 'Следующие повывшения'},
        ),
    ]
